[tool.poetry]
name = "pepp-forth"
version = "0.1.0"
description = ""
authors = ["Matthew McRaven <matthew.mcraven@gmail.com>"]
readme = "README.md"
packages = [{include = "p4"}]

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
