pull_request_rules:
  - name: "Automatic merge for Matthew when CI passes"
    conditions:
      - "author=matthew-mcraven"
      - "check-success=Linux CI"
      - "base=main"
    actions:
      merge:
