stages:
  - build
  - test
  - tag
  - deploy

# Variables that must be injected into every pipeline
variables:
  BUILD_VERSION: v0.6.0
  GIT_LFS_SKIP_SMUDGE: '1'
  # Append dist, because I have generated files there
  SAST_EXCLUDED_PATHS: spec, test, tests, tmp, dist

# Pin to a known-good version so that CI can't spontaneously break.
include:
  remote: https://gitlab.com/pepnext/config/ci/-/raw/e2cec9ecff4b2dc0e5f68baa49d66380246ecf2a/logic-mixed.yml
