name: 'Install CMake & Qt'
inputs:
  qt_version:
    required: true
    default: '6.6.0'
  cache-key-prefix:
    required: false
runs:
  using: "composite"
  # Selectively install and configure LLVM
  steps:
  - name: Install CMake and Ninja
    uses: lukka/get-cmake@v3.27.9
  - name: Install Qt
    uses: jurplel/install-qt-action@v3
    with:
      version: ${{ inputs.qt_version }}
      cache: true
      extra: "--base https://mirrors.ocf.berkeley.edu/qt"
      tools: "tools_ifw"
