stages:
  - deploy

# Variables that must be injected into every pipeline
variables:
  BUILD_VERSION: v0.6.0
  GIT_LFS_SKIP_SMUDGE: '1'


#######################
# Conditional Publish #
#######################
publish:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  image: registry.gitlab.com/pepnext/docker/develop:${BUILD_VERSION}
  stage: deploy
  needs: [ build ]
  tags:
    - docker
  script:
    - npm ci
    - export published_version=$(npm view @pepnext/tsconfig version || echo "0.0.0")
    - export current_version=$(jq -r .version < package.json)
    - npm i -g semver
    - export NODE_PATH=`npm config get prefix`/lib/node_modules/
    - printf "\n//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "const s=require('semver');process.exit(s.gt('$current_version', '$published_version'))" | node - || npm publish