name: 'Install Clang build analyzer'
# Analyze build times only if clang
# If clang build analyzer is no longer working, try ninjatracing
# See: git clone https://github.com/nico/ninjatracing
runs:
  using: "composite"
  steps:
  - name: Download Clang build analyzer
    shell: bash
    run: >
      git clone https://github.com/aras-p/ClangBuildAnalyzer
      && cd ClangBuildAnalyzer
      && cmake -B . -S . && cmake --build .
  - name: Run Clang build analyzer
    shell: bash
    run: >
      ClangBuildAnalyzer/ClangBuildAnalyzer --all build /trace.json
      && ClangBuildAnalyzer/ClangBuildAnalyzer --analyze /trace.json
      && find build -name "*json" -print
  - name: Upload clang build trace
    uses: actions/upload-artifact@v3
    with:
      name: clang-time-trace
      path: /trace.json
      retention-days: 3
      if-no-files-found: error
