name: CI
on: [push]
jobs:
  branch_info:
    name: Gather branch info
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.branch.outputs.branch }}
      not_default: ${{ steps.branch.outputs.not_default }}
    steps:
      - name: set branch info
        id: branch
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            export BRANCH="${GITHUB_REF##*/}"
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            export BRANCH="${$GITHUB_BASE_REF}"
          else
            echo "unknown event" && exit 1;
          fi
          if [ "$BRANCH" = "main" ]; then
            echo "not_default=false" >> $GITHUB_OUTPUT
          else
            echo "not_default=true" >> $GITHUB_OUTPUT
          fi
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
          echo "Output is:"
          cat $GITHUB_OUTPUT
  build_docs:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/matthew-mcraven/pepp/dev:v0.9.0-docs"
    steps:
    # Must exectute before any repo-local actions
    - uses: actions/checkout@v3
    # Install dependencies based on enabled features
    - if: env.ACT
      uses: ./.github/actions/install-node
    # No need to check out submodules, since we only build our own docs
    - name: Configure cmake for docs
      run: cmake -B build -S . -DONLY=DOC -DDOC_AUDIENCE=APP
    - run: cmake --build build && ls build/docs
    - uses: actions/upload-artifact@v3
      with:
        name: app-docs
        path: build/docs
        retention-days: 1
  start_matrix:
    needs: [branch_info, build_docs]
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: true
      # If you want to update images, must replace *ALL* images in the matrix manually.
      # Trying to use `env` or inputs will fail in this context.
      matrix:
        config:
        - {name: "Ubuntu 22.04; GCC", cache_name: 'ubuntu-gcc', runs-on: "ubuntu-latest", image: "ghcr.io/matthew-mcraven/pepp/dev:v0.9.0", compiler_launcher: "ccache", compiler_c: "", compiler_cpp: "", cmake_generator: "Ninja"}
        # Do CodeQL in clang run, to prevent needing yet another target.
        - {name: "Ubuntu 22.04; Clang 17.0", cache_name: 'ubuntu-clang', runs-on: "ubuntu-latest", image: "ghcr.io/matthew-mcraven/pepp/dev:v0.9.0", triplet: "x64-linux-clang", compiler_launcher: "", compiler_c: "clang", compiler_cpp: "clang++" , cmake_generator: "Ninja"}
        - {name: "Ubuntu 22.04; EMSDK 3.1.37", cache_name: 'ubuntu-emsdk', runs-on: "ubuntu-latest", image: "ghcr.io/matthew-mcraven/pepp/dev:v0.9.0-wasm", cmake_toolchain: '$Qt6_DIR/qt.toolchain.cmake', cmake_xargs: '-D QT_HOST_PATH=/qt/6.6.0/gcc_64 -D Boost_INCLUDE_DIR=/usr/local/include', docs_audience: 'WEB'}
        # See: https://bugreports.qt.io/browse/QTBUG-118086
        - {name: "MacOS-11; Clang 15", cache_name: 'macos-clang', runs-on: "macos-11" , compiler_launcher: "ccache", compiler_c: '$(brew --prefix llvm@15)/bin/clang', compiler_cpp: '$(brew --prefix llvm@15)/bin/clang++', cmake_generator: "Ninja"}
        - {name: "Windows Latest; MSVC", cache_name: 'windows-msvc', runs-on: "windows-latest" , compiler_launcher: "ccache",}

    with:
      name: ${{ matrix.config.name }}
      cache_name: ${{ matrix.config.cache_name }}
      runs-on: ${{ matrix.config.runs-on || 'ubuntu-latest' }}
      image: ${{ matrix.config.image || '' }}
      triplet: ${{ matrix.config.triplet || '' }}
      cmake_xargs: ${{ matrix.config.cmake_xargs || '' }}
      cmake_generator: ${{ matrix.config.cmake_generator || '' }}
      cmake_toolchain: ${{ matrix.config.cmake_toolchain || '3rd-party/vcpkg/scripts/buildsystems/vcpkg.cmake' }}
      compiler_launcher: ${{ matrix.config.compiler_launcher || '' }}
      compiler_c: ${{ matrix.config.compiler_c  || '' }}
      compiler_cpp: ${{ matrix.config.compiler_cpp || '' }}
      codeql: ${{ !!matrix.config.codeql }}
      variant: "debug"
      not_default: ${{ !!needs.branch_info.outputs.not_default }}
      docs_audience: ${{ matrix.config.docs_audience || '' }}
      docs_artifact: ${{ (matrix.config.docs_audience && '') || 'app-docs' }}
