name: Clean orphaned cache
on:
  delete:
  workflow_dispatch:

jobs:
  remove_ccache:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    env:
      # Required for GitHub CLI to work.
      # See: https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout source code (shallow)
      uses: actions/checkout@v4
    - name: Show caches (debug)
      run: gh cache list
    - name: Get caches
      run: >
        gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"
        /repos/matthew-mcraven/pepp/actions/caches > caches.json && cat caches.json
    - name: Enumerate caches matching branch key
      run: jq -rc '.actions_caches[] | select( .ref | endswith("${{ github.event.ref }}")) | select( .key | match("ccache")).key' caches.json > ccache_keys.txt
    - name: Delete cache keys
      run: xargs -i -a ccache_keys.txt -t gh cache delete {}
    - name: Debug show caches
      run: gh cache list
