name: CI for generic platform
run-name: generic_ci
on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      script-ext:
          required: true
          type: string

jobs:
  branch_info:
    uses: ./.github/workflows/metadata.yml
  build:
    runs-on: ${{ inputs.runs-on }}
    needs: branch_info
    env:
      BRANCH_NAME: ${{ needs.branch_info.outputs.branch_name }}
      NOT_DEFAULT: ${{ needs.branch_info.outputs.not_default }}
    steps:


      - name: Select newer version of clang on MacOS
        if: ${{ contains(inputs.runs-on, 'macos') }}
        run: echo "CMAKE_EXTRA_CONFIG_ARGS=-D CMAKE_C_COMPILER=$(brew --prefix llvm@15)/bin/clang -D CMAKE_CXX_COMPILER=$(brew --prefix llvm@15)/bin/clang++" >> $GITHUB_ENV

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@v3.27.7
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'
      # Windows CI does not ship with python debug libraries, so must disable those tests.
      - name: Point to new python on Windows
        if: ${{ contains(inputs.runs-on, 'windows') }}
        shell: bash
        run: >
            echo "CMAKE_EXTRA_CONFIG_ARGS=-D SKIP_TERM_TESTS=true" >> $GITHUB_ENV

        # Perform shallow clone, which may break some other operations
      - name: Checkout source code (shallow)
        uses: actions/checkout@v3
        with:
          submodules: 'true'

        # CMake configure & build
      - name: Configure vcpkg and convert shallow clone to regular
        shell: bash
        run: >
            cd $GITHUB_WORKSPACE/3rd-party/vcpkg
            && git fetch --unshallow
            && ./bootstrap-vcpkg.${{ inputs.script-ext }}
            && ./vcpkg integrate install
      - name: Configure CMake
        shell: bash
        run: >
            cmake -B build -S .
            -D CMAKE_TOOLCHAIN_FILE=3rd-party/vcpkg/scripts/buildsystems/vcpkg.cmake
            $CMAKE_EXTRA_CONFIG_ARGS
            -DCMAKE_BUILD_TYPE=Debug
      - name: Run build
        run: cmake --build build -j6 --config Debug $CMAKE_EXTRA_BUILD_ARGS


      - name: Run tests
        shell: bash
        run: cd build && ctest -j6 -C Debug -vv -o LastLog.log || (cat LastTest.log exit 1)
        env:
          # Must be offscreen, or tests that involve GUI libraries will fail
          QT_QPA_PLATFORM: 'offscreen'
          CTEST_OUTPUT_ON_FAILURE: 'TRUE'
