name: CI Build
run-name: CI Build
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest #[self-hosted, linux]
    container:
      image: ghcr.io/matthew-mcraven/pepp/dev:0.8.1
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: hendrikmuhs/ccache-action@v1.2.10
      - run: $GITHUB_WORKSPACE/3rd-party/vcpkg/bootstrap-vcpkg.sh && $GITHUB_WORKSPACE/3rd-party/vcpkg/vcpkg integrate install
      - name: Run CMake
        uses: lukka/run-cmake@v3
        with:
          buildDirectory: '$GITHUB_WORKSPACE/build'
          cmakeAppendedArgs: '-DCMAKE_ENABLE_WEBRTC:BOOL=ON -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/3rd-party/vcpkg/scripts/buildsystems/vcpkg.cmake -GNinja'
          cmakeBuildType: 'RelWithDebInfo'
      - run: cd ${{github.workspace}}/build && ctest -j $(nproc)
        env:
          QT_QPA_PLATFORM: 'offscreen'
          CTEST_OUTPUT_ON_FAILURE: 'TRUE'
          USE_SYSTEM_BOOT: 'ON' #Don't let vcpkg install boost

