name: CI Build
run-name: CI Build
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest #[self-hosted, linux]
    container:
      image: registry.gitlab.com/pepnext/docker/develop:v0.6.0
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@v1.3.0
        with:
          packages: python3-pip zstd build-essential libgl1-mesa-dev libgstreamer-gl1.0-0 libpulse-dev libxcb-glx0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-util1 libxcb-xfixes0 libxcb-xinerama0 libxcb1 libxkbcommon-dev libxkbcommon-x11-0 libxcb-xkb-dev
          version: 'apt-cache'
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: test
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: install-qt-action
          key: install-qt-action
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'
          cache: 'true'
          setup-python: 'false'
          dir: $RUNNER_WORKSPACE/qt
          set-env: 'true'
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - run: export BOOST_ROOT=/usr/local/lib
      - run: export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
      # Must set platform, because the container is non-gui
      - run: export QT_QPA_PLATFORM=offscreen
      - run: cmake -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache -B ../build .
      - run: export CTEST_OUTPUT_ON_FAILURE=TRUE
      - run: cd ../build && make -j && (make -j test || (cat ../build/Testing/Temporary/LastTest.log && exit 1))
