name: CI Build
run-name: CI Build
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest #[self-hosted, linux]
    container:
      image: registry.gitlab.com/pepnext/docker/develop:v0.6.0
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - run: apt-get install -y python3-pip zstd
      - name: test
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: install-qt-action
          key: install-qt-action
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'
          cache: 'true'
          setup-python: 'false'
          dir: $RUNNER_WORKSPACE/qt
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - run: export BOOST_ROOT=/usr/local/lib
      # Run CMake with the compiler cache
      - name: build with cmake
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeAppendedArgs: '-D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache'
          buildWithCMake: true
          buildDirectory: '${{ github.workspace }}/../build'
      - run: export CTEST_OUTPUT_ON_FAILURE=TRUE
      # Must set platform, because the container is non-gui
      - run: export QT_QPA_PLATFORM=offscreen && cd ../build && (make -j test || (cat ../build/Testing/Temporary/LastTest.log && exit 1))
