name: CI Build
run-name: CI Build
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest #[self-hosted, linux]
    container:
      image: ghcr.io/matthew-mcraven/pepp/dev:0.8.2
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Replace ld with mold
        run: pth=$(which ld) && rm $pth && ln -s $(which mold) $pth
      - uses: hendrikmuhs/ccache-action@v1.2.10
      - name: Configure vcpkg
        run: $GITHUB_WORKSPACE/3rd-party/vcpkg/bootstrap-vcpkg.sh && $GITHUB_WORKSPACE/3rd-party/vcpkg/vcpkg integrate install
      - name: Configure CMake
        run: cmake -B $GITHUB_WORKSPACE/build -S $GITHUB_WORKSPACE \
                -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache \
                -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/3rd-party/vcpkg/scripts/buildsystems/vcpkg.cmake \
                -GNinja -DCMAKE_BUILD_TYPE=Debug \
                -DCMAKE_C_FLAGS="-g -O0" -DCMAKE_CXX_FLAGS="-g -O0"
      - name: Run build
        run: cmake --build $GITHUB_WORKSPACE/build -j6
      - name: Run tests
        run: cd $GITHUB_WORKSPACE/build && ctest -j6
        env:
          QT_QPA_PLATFORM: 'offscreen'
          CTEST_OUTPUT_ON_FAILURE: 'TRUE'
          USE_SYSTEM_BOOT: 'ON' #Don't let vcpkg install boost

